### ISSUE TITLE
Lucene index cursor is null.

### ISSUE THREAD

**Issue by Lybrial** [orientechnologies/orientdb-lucene#14]
Im using:

![unbenannt](https://cloud.githubusercontent.com/assets/1107610/3243266/3f024592-f156-11e3-89e8-7db436abc679.png)

I created a new vertex type with a new property (EMBEDDEDLIST of type STRING)
and put an lucene fulltext index over the new property.

![unbenannt](https://cloud.githubusercontent.com/assets/1107610/3243346/2c1500b8-f157-11e3-8769-aa72a9ceda8c.png)

When i now want to get all key of the index:

![unbenannt](https://cloud.githubusercontent.com/assets/1107610/3243375/8c8edfe0-f157-11e3-8de5-145d0562570c.png)

The cursor is null. The rest of the informations are coorect:

![unbenannt](https://cloud.githubusercontent.com/assets/1107610/3243389/b98d1c5a-f157-11e3-870d-fcee14cfe832.png)

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5202
