### ISSUE TITLE
Indexes management

### ISSUE THREAD

**Issue by carloprad** [orientechnologies/orientdb-lucene#3]
It might be very ufesul a dedicated, studio-integrated web console in order to:

- analyze indexes status (fragmentation, memory allocation, hit ratio, open files, ...)
- customize indexes properties (cache size, page truncation, merge factor, ...)
- schedule indexes rebuild
- dictionaries management
- define analyzers
- define characters set

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5207
