### ISSUE TITLE
Dropping spatial indexes does not remove the luceneIndexes/ data

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb-lucene#36]
As noted on issue #35. I can reproduce this reliable on snapshot 2.0.

**Comment by maggiolo00** [comment]
Is this yet valid? or is it resolved with 2.0-rc2?

**Comment by maggiolo00** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
