### ISSUE TITLE
Memory leaks with PointImpl

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb-lucene#40]
Ever since recompiling a few days ago (after the iterator changes) I am running into leaks doing UPDATE queries on edges with spatial indexes.

![dump](https://cloud.githubusercontent.com/assets/1020708/5697349/5b6a6f58-99a2-11e4-9f30-7b6840d5904f.png)

I can send a heap dump if really needed.

**Comment by maggiolo00** [comment]
@AaronSchulz  

does it happen only in update or also in select queries?
What happen if you force GC?

**Comment by AaronSchulz** [comment]
I already did a GC before the screenshot.

Actually it was indeed doing fine until I tried a SELECT with AROUND just now that timed out. That seems to be the real problem then, not the UPDATES.

**Comment by maggiolo00** [comment]
ok 
thanks i will profile it

**Comment by maggiolo00** [comment]
@AaronSchulz 

i'm profiling it,  is not the new iterator that bring this memory leaks.
Was present in previous releases, and i'm not sure that is a memory leaks
I think it is a Lucene Spatial Cache. 
I'm investigating now

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5199
