### ISSUE TITLE
Boosts in multi field index

### ISSUE THREAD

**Issue by fmarsoni** [orientechnologies/orientdb-lucene#42]
It would be a nice enhancement to have boosts support when querying a lucene index

public MultiFieldQueryParser(Version matchVersion, String[] fields, Analyzer analyzer, **Map\<String,Float\> boosts**)

Right now we can send queries like this:
+(title:term1^5.0 body:term1^10.0) +(title:term2^5.0 body:term2^10.0)

But using lucene support for this would be better.

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5198
