### ISSUE TITLE
Searching on indexed fields that are long or datetime return zero results

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb-lucene#50]
When creating a lucene index on a long or datetime field, it appears that the index is created without problem but searching using that index returns zero results.

```sql
create class test extends v
create property test.long1 long
create index test.long1 fulltext engine lucene
create vertex test set long1 = 12345

select from test where long1 lucene '12345'
select from test where long1 lucene 12345
```

Both select query return zero results.

**Comment by maggiolo00** [comment]
@Ziink 
For now only text indexing is supported
For numeric just use OrientDB default indexes

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5195
