### ISSUE TITLE
getVersion() returns 0 => Assertion error

### ISSUE THREAD

**Issue by mkalus** [orientechnologies/orientdb-lucene#54]
I am not quite sure if this is an error or expected behaviour in version 2.1-rc3  (development branch). Class com.orientechnologies.lucene.OLuceneIndexEngine contains a getter getVersion returning 0. This leads to an assertion error in the updateConfiguration() method of OIndexAbstract which contains the line

```Java
assert indexEngine.getVersion() > 0;
```

Might need to be fixed.

**Comment by maggiolo00** [comment]
fixed here
https://github.com/orientechnologies/orientdb-lucene/commit/77e2c4f615e2a6bfc62e75ca1e81ba750805e5ba
