### ISSUE TITLE
[DROP DATABASE] org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed

### ISSUE THREAD

**Issue by simper66** [orientechnologies/orientdb-lucene#61]
I created a new Database with a new Class with a Lucene Text and a Spatial index.

CREATE DATABASE remote:localhost:2424/xLocation root qaz plocal graph;
CREATE CLASS Location EXTENDS V;
CREATE PROPERTY Location.searchBy string;
CREATE PROPERTY Location.lat double;
CREATE PROPERTY Location.lon double;
ALTER CLASS Location STRICTMODE=true;
CREATE INDEX Location.searchBy ON Location (searchBy) FULLTEXT ENGINE LUCENE;
CREATE INDEX Location.lat_lon ON Location(lat, lon) SPATIAL ENGINE LUCENE;
DROP DATABASE remote:localhost:2424/xLocation root qaz;

Everything goes OK.

Then I try to drop the database and I get an error. The server output and the server log shows nothing.

This is the full output of the script:

Creating database [remote:localhost:2424/xLocation] using the storage type [plocal]...
Connecting to database [remote:localhost:2424/xLocation] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost:2424/xLocation
orientdb {db=xLocation}> CREATE CLASS Location EXTENDS V

Class created successfully. Total classes in database now: 11

orientdb {db=xLocation}> CREATE PROPERTY Location.searchBy string

Property created successfully with id=1

orientdb {db=xLocation}> CREATE PROPERTY Location.lat double

Property created successfully with id=2

orientdb {db=xLocation}> CREATE PROPERTY Location.lon double

Property created successfully with id=3

orientdb {db=xLocation}> ALTER CLASS Location STRICTMODE=true

Class updated successfully

orientdb {db=xLocation}> CREATE INDEX Location.searchBy ON Location (searchBy) FULLTEXT ENGINE LUCENE

Creating index...
Created index successfully with 0 entries in 0.231000 sec(s).

Index created successfully
orientdb {db=xLocation}> CREATE INDEX Location.lat_lon ON Location(lat, lon) SPATIAL ENGINE LUCENE

Creating index...
Created index successfully with 0 entries in 0.084000 sec(s).

Index created successfully
orientdb {db=xLocation}> DROP DATABASE remote:localhost:2424/xLocation root qaz

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot delete the remote storage: xLocation

Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.

Error: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed

**Comment by maggiolo00** [comment]
hi @simper66 
Which version of orientdb?

**Comment by simper66** [comment]
Sorry, this is the enviroment:

OrientDB: OrientDB 2.1.0 GA Community Edition (downloaded from the web few week ago)
Lucene Plugin: 2.1. The one embebed in the distribution /plugin folder
SO: Windows7
JDK: Jdk 1.8.0_45
OrientDB Configuration: No special configuration. The one out of the box.
Mode: Standalone. server.bat

**Comment by maggiolo00** [comment]
@simper66
I've got the same exception
i've just created this test

https://github.com/orientechnologies/orientdb-lucene/commit/85d99aeb85b1ba4900a1d5dcf6db687f83199b45
Both plocal and remote passes. 

I will inspect further this exception
