### ISSUE TITLE
INSERT INTO INDEX:dictionary SET rid=(SELECT @rid...)

### ISSUE THREAD

**Issue by simper66** [orientechnologies/orientdb-lucene#62]
Hi,

Given a Vertex:

orientdb {db=xLocation}> select from root
0   |**#16:0**  |Root        |0    |0     |ROOT|ROOT|false   |false

I can put it in the dictionary this way:

orientdb {db=xLocation}> INSERT INTO INDEX:dictionary SET key='ROOT', **rid='#16:0'**
Inserted record '{rid:#16:0,key:ROOT}' in 0.003000 sec(s).

But with an inner SELECT it fails:

orientdb {db=xLocation}> INSERT INTO INDEX:dictionary SET key='ROOT', **rid=(select @rid from root where name ='ROOT' limit 1)**

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.insert INTO INDEX:dictionary SET key='ROOT', rid=(select @rid from root where name ='ROOT' limit 1)

Error: java.lang.ClassCastException: com.orientechnologies.orient.core.sql.OCommandSQL cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable

Enviroment:

OrientDB: OrientDB 2.1.0 GA Community Edition
SO: Windows7
JDK: Jdk 1.8.0_45
OrientDB Configuration: No special configuration. The one out of the box.
Mode: Standalone. server.bat

**Comment by maggiolo00** [comment]
hi @simper66 
this is not a lucene issue
can you open it on orientdb project?

**Comment by simper66** [comment]
Sorry Enrico. 

Opened in orientdb project.
