### ISSUE TITLE
Accents insensitive

### ISSUE THREAD

**Issue by LennyKruger** [orientechnologies/orientdb-lucene#64]
Hi all,

I have a `Person` vertex class in schema with a `firstname` property, indexed with Lucene.

I'm looking for a `Person` called **Ève**.

I'd like to retrieve my record when I do : 

```SQL
SELECT FROM Person WHERE firstname LUCENE 'è*'
```
or
```SQL
SELECT FROM Person WHERE firstname LUCENE 'é*'
```
or
```SQL
SELECT FROM Person WHERE firstname LUCENE 'e*'
```
or
```SQL
SELECT FROM Person WHERE firstname LUCENE 'E*'
```

What'd be the right analyzer or the settings to apply for this behaviour ?

Thanks !

**Comment by robfrank** [comment]
This is more a question than a bug report. 
Could you please post your question to the official ML?

https://groups.google.com/forum/#!forum/orient-database

Thanks!

**Comment by LennyKruger** [comment]
Hi @robfrank,

I'll do that. bye
