### ISSUE TITLE
Add support for all possible Lucene query types

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-lucene#68]
I am going to be adding improvement requests as per Frank's request here.

https://groups.google.com/forum/#!topic/orient-database/9SaUrGvA8Vg 

This is also with little knowledge of what ODB can do with Lucene currently. If ODB can do the suggestions, I apologize up front for the bit of extra work. 

So, first request. 

I'd like to be able to query Lucene anyway Lucene offers. This includes phrase queries, wildcard queries, proximity queries, range queries, etc.

Scott

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5189
