### ISSUE TITLE
Diverse Lucene options

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-lucene#71]
I am throwing the rest into this one issue as I feel they are a bit more exotic. We can always pull then into their own issues later, should there be more interest. I believe a couple were already suggested too.

 - fielded searching (e.g. title, author, contents)
 - flexible faceting, highlighting, joins and result grouping
 - sorting by any field
 - allow simultaneous update and searching
 - fast, memory-efficient and typo-tolerant suggesters

Scott

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5186
