### ISSUE TITLE
Index resolve with dotted notation

### ISSUE THREAD

**Issue by maggiolo00** [orientechnologies/orientdb-lucene#74]

**Comment by eddyfosman** [comment]
I have a class named Word and property "writing " with lucene index. The second class name Language with property 'abbreviation' like 'en','ja','es'... The edge "word_language" is linked between them.
I just wonder why this query works perfectly:

select out.writing from word_language  where in.abbreviation = 'en' and out in (select from Word where writing lucene 'tru*')

but in this query, nothing is returned:

select out.writing from word_language  where in.abbreviation = 'en' and out.writing lucene 'tru*'

I'm using version 2.1.3.
